app/urls.py
from django.urls import path

from . import views

app_name='app'
urlpatterns = [
    path('', views.index, name='index'),
    path('nyoba', views.nyoba, name='index'),
    path('menu', views.halaman_menu, name='halaman_menu'),
    path('menu/identitas-kami', views.halaman_identitas, name='halaman_identitas'),
    path('menu/just-reminder', views.halaman_reminder, name='halaman_reminder'),
    path('menu/narasi-harian', views.halaman_narasi, name='halaman_narasi'),
    path('menu/panduan-mu', views.halaman_panduan, name='halaman_panduan'),
    path('menu/upcoming-event', views.halaman_upcoming, name='halaman_upcoming'),
    path('menu/chant', views.halaman_chant, name='halaman_chant'),
]

ldmk2019/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 

app/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama = models.CharField(max_length=100)
    tanggal = models.DateField(auto_now=False)
    waktu = models.TimeField(auto_now=False)
    deskripsi = models.TextField()
    foto = models.ImageField(upload_to='kegiatan/%Y%m%d/', blank=True)

    class Meta:
       ordering = ['-tanggal', '-waktu']

    def __str__(self):
        return self.nama


class Info(models.Model):
    judul = models.CharField(max_length=100)
    waktu_published = models.DateTimeField(auto_now=True)
    isi = models.TextField()

    def __str__(self):
        return self.judul

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from app.models import *

# Create your views here.

def index(request):
    kegiatan = Kegiatan.objects.all()
    data = {'kegiatan':kegiatan}
    return render(request, 'app/Welcome.html', data)

def nyoba(request):
    info = Info.objects.all()
    kegiatan = Kegiatan.objects.all()
    data = {'info':info, 'kegiatan':kegiatan}
    for i in kegiatan:
        print(i.foto.url)
    return render(request, 'app/nyoba.html', data)

def halaman_menu(request):
    return render(request, 'app/halaman_menu.html')

def halaman_chant(request):
    return render(request, 'app/halaman_chant.html')

def halaman_identitas(request):
    return render(request, 'app/halaman_identitas.html')

def halaman_reminder(request):
    return render(request, 'app/halaman_reminder.html')

def halaman_narasi(request):
    return render(request, 'app/halaman_narasi.html')

def halaman_panduan(request):
    return render(request, 'app/halaman_panduan.html')

def halaman_upcoming(request):
    return render(request, 'app/halaman_upcoming.html')

app/templates/app/Welcome.html
{% extends 'app/base/base.html' %}
{% load static %}

{% block content %}
<div id="container1">
    <div id="headercontainer">
        <div id="imgcontainer">
            <img id="img-home" src="../../static/app/images/welcome1.JPG"/>
        </div>
        <div id="welcomecontainer">
            <div id="welcomee">
                <p id="welcome">selamat <br><span id="underline">datang</span></p>
            </div>
            <div id="containerdesc">
                <p id="desc"><span id="ldmk">LDMK FIA UI</span></p>
                <p id="desc">tempat pertama dimana semua mahasiswa baru UI dapat <span id="tebel">mengenal, mengalami, dan merasakan</span>
                berbagai pengetahuan dan kemampuan yang mereka butuhkan nantinya ketika menjalani dunia perkuliahan</p>
            </div>
        </div>
    </div>
    <div class="container-arrow-down">
        <i class="material-icons md-36 arrow tentang-arrow">arrow_downward</i>
    </div>
</div>

<div class="tentang-container">
    <h2>TENTANG LDMK</h2>
    <div class="tentang-ldmk-content">
    <div class="deskripsi-tentang-ldmk">
        <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus."
        </p>
    </div>
    <div class="foto-tentang-ldmk-container">
        <img src="{% static 'app/images/dumi.jpg' %}" alt="" id="foto-tentang">
    </div>
    </div>
</div>

<div class="kegiatan-dan-booklet">
    <div class="wrapper-kegiatan">
        <h2>JADWAL KEGIATAN</h2>
        <div class="container-kegiatan">
            {% for satu_kegiatan in kegiatan %}
                <div class="kegiatan-card" id="{{ satu_kegiatan.id }}">
                    <div class="tanggal-kegiatan">
                        {{ satu_kegiatan.tanggal }}
                    </div>
                    <div class="nama-kegiatan">
                        {{ satu_kegiatan.nama }}
                    </div>
                </div>

                <div class="detil-kegiatan" id="{{ satu_kegiatan.id }}" >
                    <i class="material-icons close-detil">close</i>
                    <img class="foto-detil-kegiatan" src="{{ satu_kegiatan.foto.url }}" alt="">
                    <div class="judul-dan-tanggal">
                        <h2>{{ satu_kegiatan.nama }}</h2>
                        <h4>{{ satu_kegiatan.waktu }}</h4>
                    </div>
                    <div id="deskripsi-kegiatan">
                        {{ satu_kegiatan.deskripsi|safe }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="wrapper-booklet">
        <h2>BOOKLET</h2>
        <div class="container-booklet">
            <img src="{% static 'app/images/Cover Booklet sementara.png' %}" alt="" id="icon-booklet">
        </div>
        <a href="https://drive.google.com/open?id=1UwiPUrbDDiLUEJweNhFveBh9uZ-Zui5K" download class="hidden">Download</a>
    </div>

</div>

{% endblock content %}

app/templates/app/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style type="text/css" href="css/normalize.css" rel="stylesheet"></style>
    <style type="text/css" href="css/skeleton.css" rel="stylesheet"></style>
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins|Yeseva+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'app/action.js' %}"></script>
    
    <title>{% block title %}LDMK FIA UI 2019{% endblock  %}</title>
</head>
<body>
    <div id="header">
        {% include 'app/base/header.html' %}
    </div>

    <div id="content">
        {% block content %}{% endblock content %}
    </div>

    {% comment %} <div id="footer">
        {% include 'app/base/footer.html' %}
    </div> {% endcomment %}


</body>
</html>

app/templates/app/base/header.html
<div class="burger-nav">
    <hr class="burger-hr" id="first">
    <hr class="burger-hr" id="middle">
    <hr class="burger-hr" id="second">
</div>
<div class="tombols hide-tombols" id="container-tombol">
        <div class="tombol">
            <a href="/" class="a-tombol">BERANDA</a>
        </div>
        <div class="tombol">
            <a href="#" class="a-tombol tentang-arrow">TENTANG LDMK</a>
        </div>
        <div class="tombol" id="menu">
            <div class="menu-arrow">
                <div class="menu-dan-tombol">
                    <a href="/menu" class="a-tombol">MENU</a>
                    <i class="material-icons">keyboard_arrow_down</i>
                </div>
                <div id="hide">
                    <div class="hidden-menu">
                        <a href="/menu/identitas-kami" class="a-tombol">Identitas Kami</a>
                        <a href="/menu/just-reminder" class="a-tombol">Just Reminder</a>
                        <a href="/menu/narasi-harian" class="a-tombol">Narasi Harian</a>
                        <a href="/menu/panduan-mu" class="a-tombol">Panduanmu</a>
                        <a href="/menu/upcoming-event" class="a-tombol">Upcoming Events</a>
                    </div>
                </div>
            </div>
        </div>
</div>

app/templates/app/halaman_chant.html
{% extends 'app/base/base.html' %}
{% load static %}

{% block content %}
<div>
    <div id="chantheader">
        <img id="id_kami" src="../../static/app/images/id_kami.png">
        <h1>CHANT</h1>
    </div>
    <div id="chantcontainer">

        <div id="chant1">
            <div id="video">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/HpvvfBu66xc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div id="chantlirik">
                    <p id="chant1lirik"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
                            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
            </div>  
        </div>

        <div id="chant1">
            <div id="video">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/HpvvfBu66xc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div id="chantlirik">
                    <p id="chant1lirik"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
                            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
                             sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
                </div>
        </div>

        <div id="chant1">
            <div id="video">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/HpvvfBu66xc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <div id="chantlirik">
                <p id="chant1lirik"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
            </div>
        </div>    
    </div>
</div>

{% endblock content %}

app/templates/app/halaman_identitas.html
{% extends 'app/base/base.html' %}
{% load static %}

{% block content %}

<h1>WELCOME TO HALAMAN IDENTITAS</h1>

{% endblock content %}

app/templates/app/halaman_menu.html
{% extends 'app/base/base.html' %}
{% load static %}

{% block content %}

<div class="container">
    <div id="container" class="row center_gravity">
        <div class="block">
            <a class="transparent_button" href="{% url 'app:halaman_identitas' %}">
                <img class="logo roll" src="{% static 'app/img/identitas_kami.png' %}">
            </a>
        </div>
        <div class="block">
            <a class="transparent_button" href="{% url 'app:halaman_reminder' %}">
                <img class="logo roll" src="{% static 'app/img/just_reminder.png' %}">
            </a>
        </div>
        <div class="block">
            <a class="transparent_button" href="{% url 'app:halaman_narasi' %}">
                <img class="logo roll" src="{% static 'app/img/narasi_harian.png' %}">
            </a>
        </div>
        <div class="block">
            <a class="transparent_button" href="{% url 'app:halaman_panduan' %}">
                    <img class="logo roll" src="{% static 'app/img/panduan_mu.png' %}">
            </a>
        </div>
        <div class="block">
            <a class="transparent_button" href="{% url 'app:halaman_upcoming' %}">
                <img class="logo roll" src="{% static 'app/img/upcoming_event.png' %}">
            </a>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/app/halaman_narasi.html
{% extends 'app/base/base.html' %}
{% load static %}

{% block content %}

<h1>WELCOME TO HALAMAN NARASI HARIAN</h1>

{% endblock content %}

app/templates/app/halaman_panduan.html
{% extends 'app/base/base.html' %}
{% load static %}

{% block content %}

<h1>WELCOME TO HALAMAN PANDUANMU</h1>

{% endblock content %}

app/templates/app/halaman_reminder.html
{% extends 'app/base/base.html' %}
{% load static %}

{% block content %}

<h1>WELCOME TO HALAMAN JUST REMINDER</h1>

{% endblock content %}

app/templates/app/halaman_upcoming.html
{% extends 'app/base/base.html' %}
{% load static %}

{% block content %}

<h1>WELCOME TO HALAMAN UPCOMING EVENT</h1>

{% endblock content %}

app/templates/app/nyoba.html
{% extends 'app/base/base.html' %}


{% block content %}

{% for i in info %}
<div class="nyoba">
<p>{{i.judul}}</p>
<p>{{i.isi|safe}}</p>
</div>
{% endfor %}


<p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
</p>
<p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
</p>
<p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
</p>
<p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
</p>
<p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
</p>


{% comment %} {% for satu_kegiatan in kegiatan %}
    <div class="kegiatan-card" id="{{ satu_kegiatan.id }}">
        <div class="tanggal-kegiatan">
            {{ satu_kegiatan.waktu }}
        </div>
        <div class="nama-kegiatan">
            {{ satu_kegiatan.nama }}
        </div>
    </div>

    <div class="detil-kegiatan" id="{{ satu_kegiatan.id }}" >
        <i class="material-icons close-detil">close</i>
        <img class="foto-detil-kegiatan" src="{{ satu_kegiatan.foto.url }}" alt="">
        <div class="judul-dan-tanggal">
            <h2>{{ satu_kegiatan.nama }}</h2>
            <h4>{{ satu_kegiatan.waktu }}</h4>
        </div>
        <div id="deskripsi-kegiatan">
            {{ satu_kegiatan.deskripsi|safe }}
        </div>
    </div>
{% endfor %} {% endcomment %}



{% endblock content %}